### ISSUE TITLE
its keep running every time I open the app

### ISSUE THREAD

**Issue by hawkiq** [marica27/highlighter-coachmark#17]
How to make it run only once ? its keep running every time I launch the App

**Comment by timohtey** [comment]
I believe you can store a bool value (e.g. isOnboardedComplete) using [shared_preferences](https://pub.dev/packages/shared_preferences) when onboarding is complete. Then always check this value when launching the app.

**Comment by hawkiq** [comment]
> 
> 
> I believe you can store a bool value (e.g. isOnboardedComplete) using [shared_preferences](https://pub.dev/packages/shared_preferences) when onboarding is complete. Then always check this value when launching the app.

Sorry for late response , yup I used SharedPreferences at that time and solved my problem, thanks for help.
